# Site settings
title: 百 讯
email: passion.life.com@gmail.com
description: "We will make our life to be passion!"
baseurl: ""
url: "http://passionlife.github.io"
twitter_username: passionlife
github_username:  passionlife
facebook_username:  passionlife

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
